name: dynamic-configuration-property-source
services:
  postgresql:
    image: postgres:18.0-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pwd
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d